// Code generated by "stringer -type State -linecomment"; DO NOT EDIT.

package response

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SUCCESS-200]
	_ = x[FAIL-500]
}

const (
	_State_name_0 = "请求成功"
	_State_name_1 = "请求失败"
)

func (i State) String() string {
	switch {
	case i == 200:
		return _State_name_0
	case i == 500:
		return _State_name_1
	default:
		return "State(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
